### PR TITLE
support net 8

### PR DESCRIPTION
**Pull request by WeihanLi**
try to support .NET 8

contributes to #491

### CODE REVIEW

**Comment by pdeligia** [comment]
By the way, just enabled the CI on this PR. Seems there are some build issues, if you are able to iterate when you have time, we can retry run it.

**Comment by WeihanLi** [comment]
@pdeligia could you please help on the failed tests when you have a time, no idea why it failed 😭

**Comment by pdeligia** [comment]
> @pdeligia could you please help on the failed tests when you have a time, no idea why it failed 😭

I will try to review this and let you know, but just a heads up that it is now unlikely before end of the year (due to really busy schedule this month wrapping up high priority items before the holiday season, and also freezing any code changes for this year). We can try to merge this in Jan. Thanks a lot for your contribution!

**Comment by WeihanLi** [comment]
Thanks very much

**Comment by pdeligia** [comment]
@WeihanLi I ended up upgrading coyote to .NET 8 as part of PR https://github.com/microsoft/coyote/pull/497 (I had to do some tweaks on your PR which was much easier to work on a fresh branch that I had write access to). For this reason I am closing your PR, thanks a lot for your effort!

**Pull request closed without merging**
