### PR TITLE
reschedule before AutoResetEvent.Reset

### LINKED ISSUE #495: Reschdule after AutoResetEvent.Set
Hi developers, 

I'm wondering why coyote won't reschedule after `AutoResetEvent.Set` is called. [Currently](https://github.com/microsoft/coyote/blob/51b3db9823e42a1b5ce87189e670017de8e24215/Source/Test/Rewriting/Types/Threading/WaitHandle.cs#L434), it only enables a task that waits for the signal and continue. 

Given a program:

```C#
public static async Task Test()
{
    var autoResetEvent = new AutoResetEvent(false);
    var task = Task.Run(() =>
    {
        Console.WriteLine("Enter thread!");
        autoResetEvent.WaitOne();
        Console.WriteLine("Wait done!");
    });

    Console.WriteLine("Thread started!");
    Thread.Sleep(1000 * 2);
    autoResetEvent.Set();
    Console.WriteLine("Event set!");
    await Task.WhenAll(task);
}
```

Coyote can never schedule `Console.WriteLine("Event set!");` after `Console.WriteLine("Wait done!");` because the reschedule will only be triggered at `await Task.WhenAll(task);`.

### PR DESCRIPTION
**Pull request by aoli-al**
This fixes #495 

```
public static async Task TestConcurrentAccountCreation()
{
    var threadReady = new AutoResetEvent(false);
    var autoResetEvent1 = new AutoResetEvent(false);

    var task = Task.Run(() =>
    {
        threadReady.WaitOne(); 
        autoResetEvent1.Set();
    });

    threadReady.Set();
    Thread.Yield();  // Without this forced interleave, coyote can not identify the deadlock.
    autoResetEvent1.Reset();
    autoResetEvent1.WaitOne();

    await Task.WhenAll(task);
}
```

Manually tested with the above code. Can confirm coyote successfully identifies the bug.

### CODE REVIEW

**Comment by akashlal** [comment]
Thanks -- can you add the corresponding test for deadlock as well? Best place for it is here:
https://github.com/microsoft/coyote/blob/main/Tests/Tests.BugFinding/Synchronization/AutoResetEventTests.cs

**Comment by pdeligia** [comment]
Could you also update the hashes in this test script: https://github.com/microsoft/coyote/blob/main/Tests/compare-rewriting-diff-logs.ps1

This is because the new added test changed the expected binary-rewriting hash of the `Tests.BugFinding` project, which Coyote CI validates to make sure binary-rewriting doesn't break unexpectedly. See:
```
Error: The 'Tests.BugFinding' project's IL diff hash '786F4C49E4C7361F9D91BA0DC61E05F33E3E04BB284ACF204BB9DBD73498AFEB' is not the expected '0112C27DC0C301BA980E598C484CFABA4F881F5E91FDD74107ADE0002A6901A4'.
```
in CI: https://github.com/microsoft/coyote/actions/runs/8113588744/job/22183054931?pr=496

**Comment by pdeligia** [comment]
If everything passes, I will merge this. It was great that you added this feature under the `IsLockAccessRaceCheckingEnabled` this was the right thing to do!

**Comment by aoli-al** [comment]
It it expected that Coyote will generate different `.diff.json` on different platforms? I've tried to run `compare-rewriting-diff-logs.ps1` on Ubuntu 22.04 and Windows 11 and got different results on different platforms.

**Comment by aoli-al** [comment]
```
2024-03-04T18:36:58.0613449Z   Failed Microsoft.Coyote.BugFinding.Tests.ThreadRunTests.TestThreadStartAndJoinStress [74 ms]
2024-03-04T18:36:58.0613628Z   Error Message:
2024-03-04T18:36:58.0614179Z    State of thread '312' is Background, Stopped instead of Stopped.
2024-03-04T18:36:58.0614195Z 
2024-03-04T18:36:58.0614337Z Expected: True
2024-03-04T18:36:58.0614479Z Actual:   False
2024-03-04T18:36:58.0615186Z    at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 132
2024-03-04T18:36:58.0615702Z    at Xunit.Assert.True(Boolean condition, String userMessage) in /_/src/xunit.assert/Asserts/BooleanAsserts.cs:line 116
2024-03-04T18:36:58.0616908Z    at Microsoft.Coyote.Tests.Common.BaseTest.RunSystematicTest(Delegate test, Configuration configuration, Action`1 startIterationCallBack, Action`1 endIterationCallBack) in D:\a\coyote\coyote\Tests\Tests.Common\BaseTest.cs:line 114
2024-03-04T18:36:58.0617059Z Expected: False
2024-03-04T18:36:58.0617200Z Actual:   True
2024-03-04T18:36:58.0617324Z   Stack Trace:
2024-03-04T18:36:58.0618789Z      at Microsoft.Coyote.Tests.Common.BaseTest.RunSystematicTest(Delegate test, Configuration configuration, Action`1 startIterationCallBack, Action`1 endIterationCallBack) in D:\a\coyote\coyote\Tests\Tests.Common\BaseTest.cs:line 121
2024-03-04T18:36:58.0620595Z    at Microsoft.Coyote.Tests.Common.BaseTest.RunSystematicTest(Action test, Configuration configuration, Action`1 startIterationCallBack, Action`1 endIterationCallBack) in D:\a\coyote\coyote\Tests\Tests.Common\BaseTest.cs:line 95
2024-03-04T18:36:58.0622078Z    at Microsoft.Coyote.Tests.Common.BaseTest.Test(Action test, Configuration configuration) in D:\a\coyote\coyote\Tests\Tests.Common\BaseTest.cs:line 47
2024-03-04T18:36:58.0623393Z    at Microsoft.Coyote.BugFinding.Tests.ThreadRunTests.TestThreadStartAndJoinStress() in D:\a\coyote\coyote\Tests\Tests.BugFinding\Threads\ThreadRunTests.cs:line 66
2024-03-04T18:36:58.0624204Z    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
2024-03-04T18:36:58.0624895Z    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Here is the log for the failing test. I'm not able to reproduce it on my machine. Is this test flaky?

**Review by pdeligia — APPROVED** [review]

**Pull request merged**
