### PR TITLE
switch from using Jekyll to using mkdocs

### PR DESCRIPTION
**Pull request by lovettchris**
Also added a new tool used by get-docs to create the new mkdocs.yaml "nav" section for the API documentation.

Also simplified the home page to look more dev friendly and less marketing glitz.

To see how it looks checkout https://lovettchris.github.io/bobcat/

### CODE REVIEW

**Comment by pdeligia** [comment]
Thanks @lovettchris! Any chance we can move the `windmill_dark` directory inside docs? Just feels a bit strange to have it at the top level :) Perhaps can be `docs/theme` instead of `docs/windmill_dark`?

**Comment by lovettchris** [comment]
Yes moving the folder is done and the website still works.

**Review by pdeligia — APPROVED** [review]

**Comment by pdeligia** [comment]
Thanks @lovettchris :) Lets merge it when you are ready! (Chatted with Akash and he also agrees with the changes.)

**Comment by lovettchris** [comment]
Done!

**Pull request merged**
